# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: deploy backend

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Debug Secret Check
        run: |
          if [ -z "${{ secrets.SERVER_PASSWORD }}" ]; then
            echo "ERROR: SERVER_PASSWORD is empty!"
            exit 1
          else
            echo "SERVER_PASSWORD is set."
          fi

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Upload JAR to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "target/cz-blog-backend-1.0-SNAPSHOT.jar"
          target: "/home/weixiao/cz-blog/backend-cz-blog/"
          # 不指定这个会导致创建  /home/weixiao/cz-blog/backend-cz-blog/target/cz-blog-backend-1.0-SNAPSHOT.jar
          strip_components: 1

      - name: run backend service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: bash /home/weixiao/cz-blog/backend-cz-blog/start.sh